site_name: Tensorflow Deep Learning
site_url: https://abhi8893.github.io/tensorflow-deep-learning-mrdbourke

repo_url: https://github.com/abhi8893/tensorflow-deep-learning-mrdbourke
repo_name: abhi8893/tensorflow-deep-learning-mrdbourke

theme:
  name: material
  features:
    - navigation.instant
palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    primary: orange
    accent: orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
 - mkdocs-jupyter
 - search

nav:
  - Home: 'index.md'
  - Examples: 'examples.md'
  - Fundamentals:
    - 'Tensorflow Fundamentals': '00-tensorflow-fundamentals.ipynb'
  - Neural Network Regression:
    - 'Simple Linear Regression': '01A-tensorflow-neural-network-regression.ipynb'
    - 'Polynomial Regression with Tensorflow': '01B-tensorflow-neural-network-regression.ipynb'
    - 'Medical Cost Prediction': '01C-tensorflow-neural-network-regression.ipynb'
  - Neural Network Classification:
    - 'Tensorflow Playground Reimplementation': '02A-tensorflow-playground-reimplementation.ipynb'
    - 'Fashion MNIST': '02B-Fashion-MNIST-larger-example.ipynb'
  - Computer Vision:
    - 'Pizza Steak Classifier': '03A-Pizza-Steak-Image-Classification.ipynb'
    - '10 Food Multiclass Classification': '03B-10-Food-Multiclass-Classification.ipynb'
  - Transfer Learning:
    - 'Feature Extraction': '04-Transfer-Learning-Part1-Feature-Extraction.ipynb'
    - 'Fine Tuning': '05-Transfer-Learning-Part2-Fine-Tuning.ipynb'
    - 'Food Vision Mini': '06-Transfer-Learning-Part3-Food-Vision-Mini.ipynb'
    - 'Food Vision Big': '07-Milestone-Project-1-Food-Vision-Big.ipynb'
  - Natural Language Processing:
    - 'Disaster Tweets Classification': '08-NLP-Basics-in-Tensorflow-Disaster-Tweets.ipynb'
    - 'Restructuring PubMed Abstracts using NLP': '09-SkimLit-NLP-Milestone-Project-2.ipynb'
  - Time Series Forecasting:
    - 'Bitcoin Price Forecasting': '10-Milestone-Project-3-Time-Series-Forecasting-in-Tensorflow.ipynb'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhi8893
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishekbhatia8893/
    
